# Generated by Django 6.0 on 2025-12-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
